# server port config
server:
  port: 8001
  
# datasource config
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.123.102:1521:xe
    username: C##HEALTHTOUCH
    password: HEALTHTOUCH
    
# mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml