# server port config
server:
  port: 8001
  
# datasource config
spring:
  datasource:
    url: jdbc:oracle:thin:@DB202203221231_high?TNS_ADMIN=/Users/cota/Downloads/Wallet_DB202203221231
    driver-class-name: oracle.jdbc.OracleDriver
    username: HEALTHTOUCH
    password: Taekyung9988
    
# mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml
